services:
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: moodairy
    volumes:
      - .:/moodairy
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
