# Generated by Django 5.1 on 2025-01-21 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodairy', '0001_initial'),
        ('registrations', '0003_otp_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dairy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='moodairy.dairy'),
        ),
    ]
