# Generated by Django 5.1 on 2025-01-21 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0004_customuser_dairy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='dairy',
        ),
    ]
