# Generated by Django 5.1 on 2025-01-21 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moodairy', '0002_alter_dairy_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dairy',
            name='owner',
        ),
    ]
